version: "3.6"
services:
  web:
    image: craftcms/nginx:8.2-dev
    container_name: craft_web
    ports:
      - "${DOCKER_WEB_PUBLIC_PORT:-8080}:8080"
    env_file: .env
    environment:
      XDEBUG_CONFIG: client_host=host.docker.internal
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/app

  db:
    image: mysql
    container_name: craft_db
    ports:
      - "${DOCKER_MYSQL_PUBLIC_PORT:-3306}:3306"
    environment:
      MYSQL_DATABASE: craft
      MYSQL_USER: craft
      MYSQL_PASSWORD: craft
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  redis:
    image: redis:5-alpine
    container_name: craft_redis
    ports:
      - "${DOCKER_REDIS_PUBLIC_PORT:-6379}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]

volumes:
  db_data:
